export type InteriorStyle = 'noir' | 'original';

/** Explicit, shareable original-style preview; no preference or climate reset. */
export function getInteriorStyle(search: string): InteriorStyle {
  return new URLSearchParams(search).get('interior') === 'original' ? 'original' : 'noir';
}

export function getInteriorAssets(source: string) {
  const match = source.match(/\/climate\/(spring|summer|autumn|winter)-(morning|noon|afternoon|evening|night)\.webp$/);
  if (!match) return null;
  const [, season, time] = match;
  const light = time === 'evening' || time === 'night' ? 'night' : 'day';
  return {
    season, time,
    art: `/assets/cyberpunk/noir/${light}.webp`,
    mask: `/assets/cyberpunk/noir/${season === 'winter' ? 'winter' : 'room'}-mask.svg`,
  };
}

/** Each fading scene keeps its own original city and seasonal foreground.
 * The new artwork is visible only through the interior mask. Milky lives in a
 * separate sibling layer and is never filtered or regenerated by this module. */
export function createNoirDecorator(onFallback: () => void = () => {}) {
  let reported = false;
  return async (original: HTMLImageElement, source: string): Promise<HTMLElement> => {
    const assets = getInteriorAssets(source);
    if (!assets) return original;
    try {
      const art = new Image();
      art.decoding = 'async';
      art.alt = '';
      art.draggable = false;
      art.className = 'night-interior-art';
      art.src = assets.art;
      const mask = new Image();
      mask.src = assets.mask;
      // Keep the old decoded room until both new assets can be displayed.
      await Promise.all([art.decode(), mask.decode()]);
      art.style.maskImage = `url("${assets.mask}")`;
      const layer = document.createElement('div');
      layer.className = original.className;
      layer.dataset.season = assets.season;
      layer.dataset.time = assets.time;
      original.className = 'night-scene-background';
      layer.append(original, art);
      return layer;
    } catch {
      // Missing artwork/masks must leave a usable original scene, not a blank.
      if (!reported) { reported = true; onFallback(); }
      return original;
    }
  };
}
